import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "./api.js";
const nav = [
    { id: "dashboard", label: "Overview", icon: _jsx(Icon, { path: "M4 13h6V4H4v9Zm0 7h6v-5H4v5Zm10 0h6v-9h-6v9Zm0-16v5h6V4h-6Z" }) },
    { id: "jobs", label: "Collection jobs", icon: _jsx(Icon, { path: "M12 3v12m0 0 4-4m-4 4-4-4M5 19h14" }) },
    { id: "library", label: "Archive library", icon: _jsx(Icon, { path: "M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5v-15Zm0 15A2.5 2.5 0 0 1 6.5 18H20v3H6.5A2.5 2.5 0 0 1 4 18.5" }) },
    { id: "settings", label: "Source settings", icon: _jsx(Icon, { path: "M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5ZM19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.04 1.55V20.3h-3v-.09a1.7 1.7 0 0 0-1.04-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7 15a1.7 1.7 0 0 0-1.55-1.04H5.3v-3h.15A1.7 1.7 0 0 0 7 9.92a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.12-2.12.06.06A1.7 1.7 0 0 0 10.66 6a1.7 1.7 0 0 0 1.04-1.55V4.3h3v.15A1.7 1.7 0 0 0 15.74 6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.55 1.04h.15v3h-.15A1.7 1.7 0 0 0 19.4 15Z" }) },
];
export default function App() {
    const [page, setPage] = useState("dashboard");
    const health = useQuery({ queryKey: ["health"], queryFn: api.health, refetchInterval: 15_000, retry: 1 });
    const sources = useQuery({ queryKey: ["sources"], queryFn: api.sources, refetchInterval: 10_000 });
    const source = sources.data?.sources[0];
    return _jsxs("div", { className: "app-shell", children: [_jsxs("aside", { className: "sidebar", children: [_jsxs("div", { className: "brand", children: [_jsx("div", { className: "brand-mark", children: "AR" }), _jsxs("div", { children: [_jsx("strong", { children: "Archive Relay" }), _jsx("span", { children: "Offline preservation" })] })] }), _jsx("nav", { "aria-label": "Primary navigation", children: nav.map((item) => _jsxs("button", { className: page === item.id ? "nav-item active" : "nav-item", onClick: () => setPage(item.id), children: [item.icon, _jsx("span", { children: item.label })] }, item.id)) }), _jsxs("div", { className: "sidebar-foot", children: [_jsxs("div", { className: "status-row", children: [_jsx("span", { className: health.isSuccess ? "status-dot good" : "status-dot bad" }), _jsx("span", { children: health.isSuccess ? "API connected" : "API unavailable" })] }), _jsx("div", { className: "version", children: "Collector 0.1 \u00B7 Private" })] })] }), _jsxs("main", { children: [_jsxs("header", { className: "topbar", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "PRIVATE OFFLINE ARCHIVE" }), _jsx("h1", { children: nav.find((item) => item.id === page)?.label })] }), _jsxs("div", { className: "source-chip", children: [_jsx("span", { className: source?.paused ? "status-dot warn" : "status-dot good" }), _jsxs("div", { children: [_jsx("b", { children: source?.key ?? "No source" }), _jsx("small", { children: source ? source.paused ? "Paused" : "Collection enabled" : "Configure a source" })] })] })] }), _jsxs("div", { className: "content", children: [page === "dashboard" && _jsx(Dashboard, { source: source, onNavigate: setPage }), page === "jobs" && _jsx(Jobs, { source: source }), page === "library" && _jsx(Library, {}), page === "settings" && _jsx(Settings, { source: source })] })] })] });
}
function Dashboard({ source, onNavigate }) {
    const jobs = useQuery({ queryKey: ["jobs"], queryFn: api.jobs, refetchInterval: 5_000 });
    const works = useQuery({ queryKey: ["works"], queryFn: api.works, refetchInterval: 10_000 });
    const list = jobs.data?.jobs ?? [];
    const workList = works.data?.works ?? [];
    const active = list.filter((job) => ["queued", "running"].includes(job.status));
    const totalWords = workList.reduce((sum, work) => sum + (work.words ?? 0), 0);
    const failed = list.reduce((sum, job) => sum + job.failedCount, 0);
    return _jsxs(_Fragment, { children: [_jsxs("section", { className: "hero-panel", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow accent", children: "SYSTEM SUMMARY" }), _jsx("h2", { children: "Your private archive, quietly building." }), _jsx("p", { children: "Collect conservatively, retain original captures, and move verified works into your offline OTW Archive." })] }), _jsxs("button", { className: "primary", onClick: () => onNavigate("jobs"), children: [_jsx(Icon, { path: "M12 5v14M5 12h14" }), "New collection job"] })] }), !source && _jsx(Notice, { title: "Configure your first source", text: "Create the AO3 source in Settings. New sources begin paused so nothing is requested accidentally.", action: () => onNavigate("settings") }), _jsxs("section", { className: "metric-grid", children: [_jsx(Metric, { label: "Collected works", value: formatNumber(workList.length), note: "Loaded in current view", tone: "violet" }), _jsx(Metric, { label: "Archived words", value: compactNumber(totalWords), note: "Across loaded works", tone: "cyan" }), _jsx(Metric, { label: "Active jobs", value: formatNumber(active.length), note: source?.paused ? "Source is paused" : "Worker may claim tasks", tone: "amber" }), _jsx(Metric, { label: "Terminal failures", value: formatNumber(failed), note: "Available for review", tone: failed ? "rose" : "green" })] }), _jsxs("section", { className: "two-column", children: [_jsx(Panel, { title: "Recent collection jobs", action: _jsx("button", { className: "text-button", onClick: () => onNavigate("jobs"), children: "View all \u2192" }), children: list.length ? _jsx("div", { className: "job-stack", children: list.slice(0, 5).map((job) => _jsx(JobRow, { job: job }, job.id)) }) : _jsx(Empty, { title: "No collection jobs yet", text: "Create a small ID range when you are ready." }) }), _jsx(Panel, { title: "Safety controls", children: _jsxs("div", { className: "safety-list", children: [_jsx(Safety, { label: "Source requests", value: source?.paused ? "Paused" : "Enabled", good: !source?.paused }), _jsx(Safety, { label: "Minimum delay", value: source ? `${source.minimumDelayMs / 1000}s` : "—", good: true }), _jsx(Safety, { label: "Daily request cap", value: source?.dailyRequestBudget?.toString() ?? "Unlimited", good: source?.dailyRequestBudget !== null }), _jsx(Safety, { label: "Visibility", value: "Private / restricted", good: true })] }) })] })] });
}
function Jobs({ source }) {
    const client = useQueryClient();
    const jobs = useQuery({ queryKey: ["jobs"], queryFn: api.jobs, refetchInterval: 4_000 });
    const [showForm, setShowForm] = useState(false);
    const control = useMutation({ mutationFn: ({ id, action }) => api.controlJob(id, action), onSuccess: () => client.invalidateQueries({ queryKey: ["jobs"] }) });
    return _jsxs(_Fragment, { children: [_jsxs("div", { className: "page-actions", children: [_jsxs("div", { children: [_jsx("h2", { children: "Durable collection queue" }), _jsx("p", { children: "Jobs survive worker and API restarts. Source limits apply across every worker." })] }), _jsxs("button", { className: "primary", disabled: !source, onClick: () => setShowForm(true), children: [_jsx(Icon, { path: "M12 5v14M5 12h14" }), "New job"] })] }), showForm && source && _jsx(JobForm, { source: source, onClose: () => setShowForm(false) }), _jsx(Panel, { title: "All jobs", children: jobs.data?.jobs.length ? _jsx("div", { className: "table-wrap", children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Job" }), _jsx("th", { children: "Range" }), _jsx("th", { children: "Status" }), _jsx("th", { children: "Progress" }), _jsx("th", { children: "Created" }), _jsx("th", { children: _jsx("span", { className: "sr-only", children: "Actions" }) })] }) }), _jsx("tbody", { children: jobs.data.jobs.map((job) => _jsxs("tr", { children: [_jsxs("td", { children: [_jsxs("b", { children: ["#", job.id] }), _jsx("small", { children: job.type.replace("_", " ") })] }), _jsxs("td", { children: [job.configuration.start ?? "—", "\u2013", job.configuration.end ?? "—"] }), _jsx("td", { children: _jsx(Status, { status: job.status }) }), _jsx("td", { children: _jsx(Progress, { job: job }) }), _jsx("td", { children: formatDate(job.createdAt) }), _jsx("td", { children: _jsxs("div", { className: "row-actions", children: [job.status === "running" && _jsx("button", { onClick: () => control.mutate({ id: job.id, action: "pause" }), children: "Pause" }), job.status === "paused" && _jsx("button", { onClick: () => control.mutate({ id: job.id, action: "resume" }), children: "Resume" }), !['completed', 'cancelled'].includes(job.status) && _jsx("button", { className: "danger", onClick: () => control.mutate({ id: job.id, action: "cancel" }), children: "Cancel" })] }) })] }, job.id)) })] }) }) : _jsx(Empty, { title: "The queue is empty", text: "Create a small job to begin collecting." }) })] });
}
function JobForm({ source, onClose }) {
    const client = useQueryClient();
    const [start, setStart] = useState(1);
    const [end, setEnd] = useState(10);
    const mutation = useMutation({
        mutationFn: () => api.createJob({ sourceId: source.id, start, end, batchSize: 250 }),
        onSuccess: async () => { await client.invalidateQueries({ queryKey: ["jobs"] }); onClose(); },
    });
    const count = Math.max(0, end - start + 1);
    return _jsx("div", { className: "modal-backdrop", role: "presentation", onMouseDown: (event) => event.target === event.currentTarget && onClose(), children: _jsxs("form", { className: "modal", onSubmit: (event) => { event.preventDefault(); mutation.mutate(); }, children: [_jsxs("div", { className: "modal-head", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow accent", children: "NEW COLLECTION" }), _jsx("h2", { children: "ID range job" })] }), _jsx("button", { type: "button", className: "icon-button", "aria-label": "Close", onClick: onClose, children: "\u00D7" })] }), _jsxs("p", { className: "muted", children: ["Tasks are created durably. The source is currently ", _jsx("b", { children: source.paused ? "paused" : "enabled" }), ", with a ", source.minimumDelayMs / 1000, "-second minimum delay."] }), _jsxs("div", { className: "form-grid", children: [_jsxs("label", { children: ["Starting work ID", _jsx("input", { type: "number", min: "1", value: start, onChange: (e) => setStart(Number(e.target.value)) })] }), _jsxs("label", { children: ["Ending work ID", _jsx("input", { type: "number", min: start, value: end, onChange: (e) => setEnd(Number(e.target.value)) })] })] }), _jsxs("div", { className: "estimate", children: [_jsxs("span", { children: [formatNumber(count), " tasks"] }), _jsxs("span", { children: ["\u2248 ", duration(count * source.minimumDelayMs)] })] }), mutation.error && _jsx("p", { className: "form-error", children: mutation.error.message }), _jsxs("div", { className: "modal-actions", children: [_jsx("button", { type: "button", className: "secondary", onClick: onClose, children: "Cancel" }), _jsx("button", { className: "primary", disabled: mutation.isPending || count < 1 || count > 10000, children: mutation.isPending ? "Creating…" : "Create durable job" })] })] }) });
}
function Library() {
    const works = useQuery({ queryKey: ["works"], queryFn: api.works, refetchInterval: 10_000 });
    const [filter, setFilter] = useState("");
    const list = useMemo(() => (works.data?.works ?? []).filter((work) => work.title.toLowerCase().includes(filter.toLowerCase()) || work.sourceWorkId.includes(filter)), [works.data, filter]);
    return _jsxs(_Fragment, { children: [_jsxs("div", { className: "page-actions", children: [_jsxs("div", { children: [_jsx("h2", { children: "Collected works" }), _jsx("p", { children: "Normalized records backed by immutable raw captures." })] }), _jsxs("div", { className: "search", children: [_jsx(Icon, { path: "m21 21-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z" }), _jsx("input", { "aria-label": "Filter works", placeholder: "Filter title or source ID", value: filter, onChange: (e) => setFilter(e.target.value) })] })] }), _jsx(Panel, { title: `${list.length} works in view`, children: list.length ? _jsx("div", { className: "work-grid", children: list.map((work) => _jsxs("article", { className: "work-card", children: [_jsxs("div", { className: "work-card-top", children: [_jsxs("span", { className: "source-id", children: ["AO3 #", work.sourceWorkId] }), _jsx(Status, { status: work.availability })] }), _jsx("h3", { children: work.title }), _jsxs("div", { className: "work-meta", children: [_jsxs("span", { children: [compactNumber(work.words ?? 0), " words"] }), _jsxs("span", { children: [work.expectedChapters ?? "?", " ch."] }), _jsx("span", { children: work.languageCode.toUpperCase() })] }), _jsxs("div", { className: "work-foot", children: [_jsx("span", { children: work.complete ? "Complete" : "In progress" }), _jsxs("span", { children: ["Seen ", formatDate(work.lastSeenAt)] })] })] }, work.id)) }) : _jsx(Empty, { title: "No matching works", text: "Collected works will appear here after a worker succeeds." }) })] });
}
function Settings({ source }) {
    const client = useQueryClient();
    const [delay, setDelay] = useState(source?.minimumDelayMs ?? 10000);
    const [budget, setBudget] = useState(source?.dailyRequestBudget ?? 250);
    useEffect(() => {
        if (source) {
            setDelay(source.minimumDelayMs);
            setBudget(source.dailyRequestBudget ?? 250);
        }
    }, [source?.id, source?.minimumDelayMs, source?.dailyRequestBudget]);
    const update = useMutation({ mutationFn: (paused) => source ? api.updateSource(source.id, { minimumDelayMs: delay, dailyRequestBudget: budget, paused }) : Promise.reject(new Error("No source")), onSuccess: () => client.invalidateQueries({ queryKey: ["sources"] }) });
    const create = useMutation({ mutationFn: () => api.createSource({ key: "ao3", origin: "https://archiveofourown.org" }), onSuccess: () => client.invalidateQueries({ queryKey: ["sources"] }) });
    if (!source)
        return _jsx(Panel, { title: "Create source", children: _jsxs("div", { className: "settings-empty", children: [_jsx("div", { className: "large-icon", children: _jsx(Icon, { path: "M12 3v18m9-9H3" }) }), _jsx("h2", { children: "No collection source configured" }), _jsx("p", { children: "AO3 will be created paused with a 10-second delay and 250-request daily budget." }), _jsx("button", { className: "primary", onClick: () => create.mutate(), children: create.isPending ? "Creating…" : "Create paused AO3 source" })] }) });
    return _jsxs("div", { className: "settings-layout", children: [_jsx(Panel, { title: "Source policy", children: _jsxs("div", { className: "settings-form", children: [_jsxs("label", { children: ["Source origin", _jsx("input", { value: source.origin, disabled: true })] }), _jsxs("div", { className: "form-grid", children: [_jsxs("label", { children: ["Minimum delay (milliseconds)", _jsx("input", { type: "number", min: "2000", value: delay, onChange: (e) => setDelay(Number(e.target.value)) })] }), _jsxs("label", { children: ["UTC daily request budget", _jsx("input", { type: "number", min: "1", value: budget, onChange: (e) => setBudget(Number(e.target.value)) })] })] }), _jsxs("div", { className: "policy-callout", children: [_jsx(Icon, { path: "M12 9v4m0 4h.01M10.3 3.9 2.5 17.4A1 1 0 0 0 3.37 19h17.26a1 1 0 0 0 .87-1.5L13.7 3.9a1 1 0 0 0-1.4 0Z" }), _jsxs("p", { children: [_jsx("b", { children: "Safety boundary" }), _jsx("span", { children: "Settings are enforced transactionally across every worker. The API will not accept a delay below two seconds." })] })] }), _jsxs("div", { className: "settings-actions", children: [_jsx("button", { className: "secondary", onClick: () => update.mutate(true), children: "Save & pause" }), _jsx("button", { className: source.paused ? "primary" : "danger-button", onClick: () => update.mutate(!source.paused), children: source.paused ? "Enable collection" : "Pause immediately" })] }), update.error && _jsx("p", { className: "form-error", children: update.error.message })] }) }), _jsx(Panel, { title: "Current state", children: _jsxs("div", { className: "source-detail", children: [_jsx("span", { className: source.paused ? "orb paused" : "orb" }), _jsx("h3", { children: source.paused ? "Collection paused" : "Collection enabled" }), _jsx("p", { children: source.paused ? "Workers cannot claim new tasks from this source." : "Workers may claim tasks within the configured limits." }), _jsxs("dl", { children: [_jsxs("div", { children: [_jsx("dt", { children: "Source key" }), _jsx("dd", { children: source.key })] }), _jsxs("div", { children: [_jsx("dt", { children: "Next request slot" }), _jsx("dd", { children: source.nextRequestAt ? formatDateTime(source.nextRequestAt) : "Available" })] }), _jsxs("div", { children: [_jsx("dt", { children: "Adult content" }), _jsx("dd", { children: "Allowed" })] }), _jsxs("div", { children: [_jsx("dt", { children: "Archive visibility" }), _jsx("dd", { children: "Private" })] })] })] }) })] });
}
function Panel({ title, action, children }) { return _jsxs("section", { className: "panel", children: [_jsxs("div", { className: "panel-head", children: [_jsx("h2", { children: title }), action] }), children] }); }
function Metric({ label, value, note, tone }) { return _jsxs("article", { className: `metric ${tone}`, children: [_jsx("span", { children: label }), _jsx("strong", { children: value }), _jsx("small", { children: note })] }); }
function Empty({ title, text }) { return _jsxs("div", { className: "empty", children: [_jsx("div", { className: "empty-mark", children: "\u00B7 \u00B7 \u00B7" }), _jsx("h3", { children: title }), _jsx("p", { children: text })] }); }
function Notice({ title, text, action }) { return _jsxs("div", { className: "notice", children: [_jsx(Icon, { path: "M12 9v4m0 4h.01M10.3 3.9 2.5 17.4A1 1 0 0 0 3.37 19h17.26a1 1 0 0 0 .87-1.5L13.7 3.9a1 1 0 0 0-1.4 0Z" }), _jsxs("div", { children: [_jsx("b", { children: title }), _jsx("span", { children: text })] }), _jsx("button", { onClick: action, children: "Open settings" })] }); }
function Safety({ label, value, good }) { return _jsxs("div", { children: [_jsxs("span", { children: [_jsx("i", { className: good ? "check" : "pause-icon", children: good ? "✓" : "Ⅱ" }), label] }), _jsx("b", { children: value })] }); }
function Status({ status }) { return _jsx("span", { className: `status ${status}`, children: status.replace("_", " ") }); }
function Progress({ job }) { const done = job.succeededCount + job.failedCount + job.skippedCount; const percent = job.discoveredCount ? Math.round(done / job.discoveredCount * 100) : 0; return _jsxs("div", { className: "progress-cell", children: [_jsx("div", { children: _jsx("span", { style: { width: `${percent}%` } }) }), _jsxs("small", { children: [done, "/", job.discoveredCount, " \u00B7 ", percent, "%"] })] }); }
function JobRow({ job }) { return _jsxs("div", { className: "job-row", children: [_jsx("div", { className: "job-icon", children: _jsx(Icon, { path: "M12 4v12m0 0 4-4m-4 4-4-4" }) }), _jsxs("div", { children: [_jsxs("b", { children: ["Job #", job.id] }), _jsxs("span", { children: [job.configuration.start ?? "?", "\u2013", job.configuration.end ?? "?", " \u00B7 ", formatNumber(job.discoveredCount), " tasks"] })] }), _jsx(Status, { status: job.status }), _jsx("time", { children: formatDate(job.createdAt) })] }); }
function Icon({ path }) { return _jsx("svg", { "aria-hidden": "true", viewBox: "0 0 24 24", children: _jsx("path", { d: path }) }); }
const formatNumber = (value) => new Intl.NumberFormat().format(value);
const compactNumber = (value) => new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(value);
const formatDate = (value) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value));
const formatDateTime = (value) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
function duration(ms) { const minutes = Math.ceil(ms / 60000); return minutes < 60 ? `${minutes} min minimum` : `${Math.floor(minutes / 60)}h ${minutes % 60}m minimum`; }
//# sourceMappingURL=App.js.map